using System;
using System.Text;
using PokemonApp.Models.Enums;

namespace PokemonApp.Models;

public class PokemonType
{
    public double normalEffectiveness;
    public double fireEffectiveness;
    public double waterEffectiveness;
    public double grassEffectiveness;
    public double flyingEffectiveness;
    public double fightingEffectiveness;
    public double poisonEffectiveness;
    public double electricEffectiveness;
    public double groundEffectiveness;
    public double rockEffectiveness;
    public double psychicEffectiveness;
    public double iceEffectiveness;
    public double bugEffectiveness;
    public double ghostEffectiveness;
    public double steelEffectiveness;
    public double dragonEffectiveness;
    public double darkEffectiveness;
    public double fairyEffectiveness;

    public PokemonType(EPokemonType.PokemonType type)
    {
        switch (type)
        {
            case EPokemonType.PokemonType.Normal:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 0.5;
                this.ghostEffectiveness = 0;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Fire:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 0.5;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 2;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 2;
                this.rockEffectiveness = 0.5;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 0.5;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 2;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Water:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 2;
                this.waterEffectiveness = 0.5;
                this.grassEffectiveness = 0.5;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 2;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 2;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 0.5;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 1;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Grass:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 2;
                this.grassEffectiveness = 0.5;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 0.5;
                this.groundEffectiveness = 2;
                this.flyingEffectiveness = 0.5;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 0.5;
                this.rockEffectiveness = 2;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 0.5;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Electric:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 2;
                this.grassEffectiveness = 0.5;
                this.electricEffectiveness = 0.5;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 0;
                this.flyingEffectiveness = 2;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 0.5;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 1;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Ice:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 0.5;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 0.5;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 2;
                this.flyingEffectiveness = 2;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 2;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Fighting:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 0.5;
                this.groundEffectiveness = 0.5;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 0.5;
                this.ghostEffectiveness = 0.5;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0;
                this.fairyEffectiveness = 2;
                break;
            case EPokemonType.PokemonType.Poison:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 0.5;
                this.groundEffectiveness = 0.5;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 0.5;
                this.ghostEffectiveness = 0.5;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0;
                this.fairyEffectiveness = 2;
                break;
            case EPokemonType.PokemonType.Ground:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 2;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 0.5;
                this.electricEffectiveness = 2;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 2;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 0;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 0.5;
                this.rockEffectiveness = 2;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 2;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Flying:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 0.5;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 2;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 2;
                this.rockEffectiveness = 0.5;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Psychic:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 2;
                this.poisonEffectiveness = 2;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 0.5;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 0;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Bug:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 2;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 0.5;
                this.poisonEffectiveness = 0.5;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 0.5;
                this.psychicEffectiveness = 2;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 0.5;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 2;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 0.5;
                break;
            case EPokemonType.PokemonType.Rock:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 2;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 2;
                this.fightingEffectiveness = 0.5;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 0.5;
                this.flyingEffectiveness = 2;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 2;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Ghost:
                this.normalEffectiveness = 0;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 2;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 2;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 0.5;
                this.steelEffectiveness = 1;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Dragon:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 2;
                this.darkEffectiveness = 0.5;
                this.steelEffectiveness = 1;
                this.fairyEffectiveness = 1;
                break;
            case EPokemonType.PokemonType.Dark:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 1;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 0.5;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 2;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 2;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 0.5;
                this.steelEffectiveness = 1;
                this.fairyEffectiveness = 0.5;
                break;
            case EPokemonType.PokemonType.Steel:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 0.5;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 0.5;
                this.iceEffectiveness = 2;
                this.fightingEffectiveness = 1;
                this.poisonEffectiveness = 1;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 2;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 1;
                this.darkEffectiveness = 1;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 2;
                break;
            case EPokemonType.PokemonType.Fairy:
                this.normalEffectiveness = 1;
                this.fireEffectiveness = 0.5;
                this.waterEffectiveness = 1;
                this.grassEffectiveness = 1;
                this.electricEffectiveness = 1;
                this.iceEffectiveness = 1;
                this.fightingEffectiveness = 2;
                this.poisonEffectiveness = 0.5;
                this.groundEffectiveness = 1;
                this.flyingEffectiveness = 1;
                this.psychicEffectiveness = 1;
                this.bugEffectiveness = 1;
                this.rockEffectiveness = 1;
                this.ghostEffectiveness = 1;
                this.dragonEffectiveness = 2;
                this.darkEffectiveness = 2;
                this.steelEffectiveness = 0.5;
                this.fairyEffectiveness = 1;
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(type), type, null);
        }
        this.normalEffectiveness = normalEffectiveness;
        this.fireEffectiveness = fireEffectiveness;
        this.waterEffectiveness = waterEffectiveness;
        this.grassEffectiveness = grassEffectiveness;
        this.electricEffectiveness = electricEffectiveness;
        this.iceEffectiveness = iceEffectiveness;
        this.fightingEffectiveness = fightingEffectiveness;
        this.poisonEffectiveness = poisonEffectiveness;
        this.groundEffectiveness = groundEffectiveness;
        this.flyingEffectiveness = flyingEffectiveness;
        this.psychicEffectiveness = psychicEffectiveness;
        this.bugEffectiveness = bugEffectiveness;
        this.rockEffectiveness = rockEffectiveness;
        this.ghostEffectiveness = ghostEffectiveness;
        this.dragonEffectiveness = dragonEffectiveness;
        this.darkEffectiveness = darkEffectiveness;
        this.steelEffectiveness = steelEffectiveness;
        this.fairyEffectiveness = fairyEffectiveness;
    }
}